### ISSUE TITLE
Version control and private key file

### ISSUE THREAD

**Issue by madshargreave** [companykitchen/big_query#13]
Hi

Is there a way to avoid committing the private key file to version control for security?

**Comment by jordan0day** [comment]
I think you should be able to set any path with
`config :big_query, bigquery_private_key_path: "/path/to/file.json"`, in your applications configuration, but I admit I haven't tried it.

If that doesn't work and/or you'd like to try to make it better, there was a recent post about configuring libraries in elixir that might have some nice insights: http://michal.muskala.eu/2017/07/30/configuring-elixir-libraries.html

I'm sure it could be done better than it is currently here, so I'd be happy to hear any suggestions.

**Comment by madshargreave** [comment]
@jordan0day There's a PR allowing to pass in the file as a string, which solves this.

Could it be mergeD?

**Comment by jordan0day** [comment]
PR #19  was merged in.

I've also opened issue #20, as configuration for this library is definitely in need of refactoring, please chime in on that issue if you have any opinions on how to make it better.
