### ISSUE TITLE
RFC - Fixing library configuration

### ISSUE THREAD

**Issue by jordan0day** [companykitchen/big_query#20]
Currently configuration in this library is pretty messy and needs to modernized, removing all of the application configuration. I'm curious if anyone has any opinions on what they'd like to see?

Currently, the following values are configurable in app config:
* `bigquery_request_timeout` - (Optional) The duration (in ms) to wait on a response from bigquery. (Defaults to 120,000 ms)
* `bigquery_scope` - (Optional) Additional scopes to provide when requesting an access token from bigquery. Current default scopes are:
  * `https://www.googleapis.com/auth/bigquery.readonly`, 
  * `https://www.googleapis.com/auth/bigquery.insertdata`, and  
  * `https://www.googleapis.com/auth/bigquery`
* `bigquery_private_key_path` - (Required if `bigquery_private_key_data` is not set) The path to the bigquery pem file used to request an access token.
* `bigquery_private_key_data` - (Required if `bigquery_private_key_path` is not set) Private key data used to request and access token.

The library has a `TokenServer` process which begins on startup and is used to cache access tokens until they expire (this saves having to request an access token for each operation).

The way I see it, the easiest change (from a user perspective) is to just add something like an agent process and a few functions to set these configuration values after the application has already started up, and then instead of fetching the configuration from app config, fetch them from the agent.

Another approach would be to change the library such that it's not an "application library" (that is, there's no application supervisor that runs on startup), and require the user to start the `TokenServer` themselves (passing in the required config info as startup arguments).

I'm sure there's several other approaches that would work equally well, so I'm just looking for opinions from users on what they'd like to see.

**Comment by Nagasaki45** [comment]
For me it makes more sense to start whatever needed manually in the root supervisor of the application and pass the configuration through `start_link`. But now when I think about it I'm not sure why one would ever want a separate application for dependencies. Is there a good reason not to start this `TokenServer` as part of the user's application?
