### ISSUE TITLE
Private key path in OTP release

### ISSUE THREAD

**Issue by Nagasaki45** [companykitchen/big_query#9]
I'm trying to deploy a project that uses this app as an OTP release, and getting confused by how should I set the `bigquery_private_key_path`.

I learned [here](https://elixirforum.com/t/is-it-possible-to-include-resource-files-when-packaging-my-project-using-mix-escript/730/10) that resources should reside in the `priv` directory, so I tried to put the file there and set the path accordingly:

```elixir
config :big_query,
  bigquery_private_key_path: "priv/my_credentials.json"
```

The problem is that `priv` moves during the creation of the release, so to find the new path I need to use either `:code.priv_dir(:my_app)` or `Application.app_dir(:my_app, "priv")`. But using these options in my `config.exs` file won't work either, because the application doesn't exist when the file compiles.

The only option I can think of to solve this is to add one more env to `big_query`, with the name of the app that hosts the credential file, and if the env exists get the file from there. Something like this:

```elixir
# config.exs

config :big_query,
  bigquery_private_key_hosted_by_app: :my_app,
  bigquery_private_key_path: "priv/my_credentials.json"
```
```elixir
# big_query/lib/big_query/access_token.ex

# ...
def get_token() do
  key_file_app = Application.get_env(:big_query, :bigquery_private_key_hosted_by_app)
  key_file = Application.get_env(:big_query, :bigquery_private_key_path)
  key_file =
    if key_file_app do
      Application.app_dir(key_file_app, key_file)
    else
      key_file
    end
  # ...
```

1. There is a good chance that I'm missing a simpler solution.
1. There is a good chance that the above doesn't solve the problem / introduce new issues that I'm not aware of.
1. It is far from being elegant.

Any ideas?

Thanks!

**Comment by jordan0day** [comment]
Sorry about the late reply, hopefully you've found a solution that will work for you by now. One approach may be to override the config value at startup via `Application.put_env/3`, or by altering the `sys.config` that is deployed with your release to point to the true location of the key file.

**Comment by madshargreave** [comment]
@Nagasaki45 how do you handle your private key and version control?

**Comment by Nagasaki45** [comment]
The key is not under version control. I added it to `.gitignore`.

My issue wasn't related to version control, but to building an OTP release with the right configuration. To solve that I forked this project and applied [this "fix"](https://github.com/Nagasaki45/big_query/commit/fd580fb035c593b9dc32e685553f2b9bcd78367e). You can see it in use [here](https://github.com/Nagasaki45/krihelinator/blob/master/config/config.exs).

Hope that this answers your question.

**Comment by madshargreave** [comment]
I see, I suppose my problem is that I build the release on a CI server which needs to have the key in the priv folder to build and the only way to do that afaik is to add it to version control

**Comment by Nagasaki45** [comment]
I see. Still, it's a different issue. I don't have a good idea for how to do that. Sorry

**Comment by ranjith965** [comment]
while executing the below query
BigQuery.Job.query("my-project-id",%BigQuery.Types.Query{kind: "bigquery#queryResponse", query: "select * from ranjith"})
am getting the below error
{:error,
 %{body: "{\n \"error\": {\n  \"errors\": [\n   {\n    \"domain\": \"global\",\n    \"reason\": \"invalid\",\n    \"message\": \"Invalid value for: null is not a valid value\"\n   }\n  ],\n  \"code\": 400,\n  \"message\": \"Invalid value for: null is not a valid value\"\n }\n}\n",
   headers: [{"Vary", "X-Origin"},
    {"Content-Type", "application/json; charset=UTF-8"},
    {"Date", "Thu, 05 Oct 2017 06:30:37 GMT"},
    {"Expires", "Thu, 05 Oct 2017 06:30:37 GMT"},
    {"Cache-Control", "private, max-age=0"},
    {"X-Content-Type-Options", "nosniff"}, {"X-Frame-Options", "SAMEORIGIN"},
    {"X-XSS-Protection", "1; mode=block"}, {"Server", "GSE"},
    {"Alt-Svc", "quic=\":443\"; ma=2592000; v=\"39,38,37,35\""},
    {"Accept-Ranges", "none"}, {"Vary", "Origin,Accept-Encoding"},
    {"Transfer-Encoding", "chunked"}], status_code: 400}}

what does it mean?? How to fix this? please help someone

**Comment by jordan0day** [comment]
Please chime in on #20 on any ways you'd like to see the configuration of this library improved.
